/**
 * A captured snapshot of the drawing.
 *
 * Neural Pulse's free tier allows 100 calls a month and there is no paid tier
 * to buy past it, so a cold instance can find itself unable to read the live
 * database. Blanking the page in that situation would be the worst answer: the
 * product would look broken when in fact its datastore is simply rate-limited.
 *
 * So the last state this app actually produced is kept here and served when the
 * live read fails. The UI labels it plainly as a snapshot — it is never passed
 * off as live data.
 *
 * Every table, column, type and rationale below was generated by the live
 * system from the three sample messages; nothing here was hand-designed.
 */

export interface SnapshotColumn {
  name: string;
  type: string;
  primary?: boolean;
  rationale: string;
}

export interface SnapshotTable {
  name: string;
  columns: SnapshotColumn[];
  rows: Record<string, unknown>[];
  rowCount: number;
}

const STRUCTURAL = "structural column";

const LEADS: SnapshotTable = {
  name: "leads",
  columns: [
    { name: "id", type: "uuid", primary: true, rationale: STRUCTURAL },
    { name: "source_message", type: "text", rationale: STRUCTURAL },
    { name: "ingested_at", type: "date", rationale: STRUCTURAL },
    { name: "company_name", type: "text", rationale: "identifies the prospective organization" },
    { name: "contact_name", type: "text", rationale: "primary point of contact" },
    { name: "email", type: "text", rationale: "contact email address for follow-up" },
    { name: "city", type: "text", rationale: "geographic market where clinics operate" },
    { name: "clinic_count", type: "number", rationale: "number of clinic locations operated" },
    { name: "monthly_budget", type: "number", rationale: "allocated monthly spend for the solution" },
    { name: "fleet_size", type: "number", rationale: "records the number of trucks operated" },
    { name: "depot_count", type: "number", rationale: "records the number of depot locations" },
    { name: "timeline", type: "text", rationale: "stores the target deployment timeframe" },
    { name: "nps", type: "number", rationale: "stores the customer's current Net Promoter Score" },
    { name: "job_title", type: "text", rationale: "stores the contact's professional role" },
    { name: "warehouse_count", type: "number", rationale: "tracks operational scale in warehouses" },
    { name: "current_system", type: "text", rationale: "records incumbent software being replaced" },
    { name: "renewal_date", type: "date", rationale: "captures contract expiration with the incumbent" },
  ],
  rows: [
    {
      _id: "dc75eb2c-5792-4d0e-8d49-9f3612a4c7b1",
      id: "dc75eb2c-5792-4d0e-8d49-9f3612a4c7b1",
      ingested_at: "2026-09-18T00:00:00.000Z",
      company_name: "Harbor Freight Collective",
      contact_name: "Elena Ruiz",
      email: "elena@harborfc.com",
      job_title: "VP Ops",
      warehouse_count: 18,
      current_system: "SAP",
      renewal_date: "2026-11-30T00:00:00.000Z",
      monthly_budget: 15000,
    },
    {
      _id: "4e1da598-7f57-44bc-bd49-7c0348e1b2aa",
      id: "4e1da598-7f57-44bc-bd49-7c0348e1b2aa",
      ingested_at: "2026-09-18T00:00:00.000Z",
      company_name: "Northwind Logistics",
      contact_name: "Raj Patel",
      email: "raj@northwind.io",
      fleet_size: 42,
      depot_count: 6,
      timeline: "before Q1",
      nps: 31,
      monthly_budget: 9000,
    },
    {
      _id: "000bb62d-956f-4fb1-a70e-f3a7cb21d004",
      id: "000bb62d-956f-4fb1-a70e-f3a7cb21d004",
      ingested_at: "2026-09-18T00:00:00.000Z",
      company_name: "Belmont Dental",
      contact_name: "Maria Chen",
      email: "maria@belmontdental.com",
      city: "Austin",
      clinic_count: 3,
      monthly_budget: 2400,
    },
  ],
  rowCount: 3,
};

const SUPPORT_TICKETS: SnapshotTable = {
  name: "support_tickets",
  columns: [
    { name: "id", type: "uuid", primary: true, rationale: STRUCTURAL },
    { name: "source_message", type: "text", rationale: STRUCTURAL },
    { name: "ingested_at", type: "date", rationale: STRUCTURAL },
    { name: "ticket_number", type: "number", rationale: "unique identifier for tracking the ticket" },
    { name: "company_name", type: "text", rationale: "customer or organization submitting the ticket" },
    { name: "issue_description", type: "text", rationale: "summary of the reported problem" },
    { name: "failure_count", type: "number", rationale: "recorded count of job failures" },
    { name: "severity", type: "text", rationale: "priority or severity level assigned to the ticket" },
    { name: "assigned_team", type: "text", rationale: "team responsible for resolving the issue" },
    { name: "first_reported_date", type: "date", rationale: "initial date the issue was reported" },
  ],
  rows: [
    {
      _id: "7a41c0de-2b19-4a77-9c52-1f8b6d3e5a20",
      id: "7a41c0de-2b19-4a77-9c52-1f8b6d3e5a20",
      ingested_at: "2026-09-18T00:00:00.000Z",
      ticket_number: 4471,
      company_name: "Acme Tooling",
      issue_description: "Export job has failed 14 times since Friday",
      failure_count: 14,
      severity: "high",
      assigned_team: "data platform team",
      first_reported_date: "2026-09-12T00:00:00.000Z",
    },
  ],
  rowCount: 1,
};

const TABLES = [LEADS, SUPPORT_TICKETS];

/** Captured on 2026-09-18, the last time the live database was readable. */
export const SNAPSHOT_TAKEN = "2026-09-18";

export function snapshotPayload(reason: string) {
  return {
    tables: TABLES,
    totalColumns: TABLES.reduce((sum, t) => sum + t.columns.length, 0),
    totalRows: TABLES.reduce((sum, t) => sum + t.rowCount, 0),
    reasoningConfigured: Boolean(
      process.env.GEMINI_API_KEY ?? process.env.ANTHROPIC_API_KEY,
    ),
    degraded: true,
    degradedReason: reason,
    snapshotTaken: SNAPSHOT_TAKEN,
  };
}
